name: Cypress Tests

on:
  push:
    branches: [master]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests  \
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
         node-version: 15
      
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
         working-directory: ./frontend
         build: npm run build
         start: npm start
